################
# DrupalCI GitLabCI template
# https://git.drupalcode.org/project/gitlab_templates/
################

include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - /includes/include.drupalci.main.yml
      - /includes/include.drupalci.variables.yml
      - /includes/include.drupalci.workflows.yml

variables:
  _TARGET_PHP: "8.2"
  _TARGET_CORE: "11.x"
  _PHPCS_DRUPAL_STANDARD: "Drupal,DrupalPractice"
  _PHPCS_EXTENSIONS: "php,module,install"
